using System;
using System.Collections.Generic;

namespace MaxConsole.DTO
{
    public partial class GsOrcamentos
    {
        public int OrcId { get; set; }
        public int AssId { get; set; }
        public int? AssdocId { get; set; }
        public int? AssdocId2 { get; set; }
        public int? AssdocId3 { get; set; }
        public int? CttId { get; set; }
        public int? ConpagId { get; set; }
        public int? CliforId { get; set; }
        public int? FunId { get; set; }
        public int? EmpId { get; set; }
        public int? NfId { get; set; }
        public int? CidId { get; set; }
        public int? CliforconId { get; set; }
        public int? NotserId { get; set; }
        public int? NomevtId { get; set; }
        public int? TiptranspId { get; set; }
        public int? OrccanId { get; set; }
        public int? OrcNum { get; set; }
        public int? OrcDiaevt { get; set; }
        public DateTime? OrcData { get; set; }
        public int? OrcSit { get; set; }
        public DateTime? OrcDatacancela { get; set; }
        public string OrcObscancela { get; set; }
        public string OrcTipo { get; set; }
        public string OrcEventoNome { get; set; }
        public string OrcEventoTipo { get; set; }
        public string OrcEventoLocal { get; set; }
        public DateTime? OrcDatini { get; set; }
        public DateTime? OrcDatfim { get; set; }
        public int? OrcVisita { get; set; }
        public DateTime? OrcVisitaData { get; set; }
        public int? OrcVisitaHora { get; set; }
        public string OrcObsint { get; set; }
        public string OrcObs { get; set; }
        public decimal? OrcValmat { get; set; }
        public int? OrcItemat { get; set; }
        public int? OrcQtdmat { get; set; }
        public decimal? OrcSubtotal { get; set; }
        public decimal? OrcValordesp { get; set; }
        public decimal? OrcValordesc { get; set; }
        public double? OrcValordescperc { get; set; }
        public int? OrcTipodesc { get; set; }
        public decimal? OrcValortotal { get; set; }
        public decimal? OrcValorfixo { get; set; }
        public decimal? OrcVlnaocobrado { get; set; }
        public decimal? OrcVlcobrado { get; set; }
        public string OrcEmailContato { get; set; }
        public DateTime? OrcValidade { get; set; }
        public string OrcEvtEnd { get; set; }
        public string OrcEvtNum { get; set; }
        public string OrcEvtCpl { get; set; }
        public string OrcEvtCep { get; set; }
        public string OrcEvtBai { get; set; }
        public int? OrcEvtCidid { get; set; }
        public string OrcEvtTel { get; set; }
        public string OrcEvtDdd { get; set; }
        public string OrcEvtContato { get; set; }
        public int? OrcIteeqt { get; set; }
        public int? OrcQtdeqt { get; set; }
        public int? OrcFixvalorc { get; set; }
        public decimal? OrcValeqt { get; set; }
        public int? OrcTabpre { get; set; }
        public DateTime? OrcDatapr { get; set; }
        public int? OrcChqclc { get; set; }
        public DateTime? OrcChqclcemi { get; set; }
        public DateTime? OrcChqclccomp { get; set; }
        public int? OrcChqclcbanid { get; set; }
        public string OrcChqclcage { get; set; }
        public string OrcChqclccc { get; set; }
        public decimal? OrcChqclcval { get; set; }
        public string OrcChqclcnum { get; set; }
        public int? OrcTabprecotip { get; set; }
        public int? OrcTabpreco { get; set; }
        public int? SysDel { get; set; }
        public DateTime? SysDatcad { get; set; }
        public int? OrcTipope { get; set; }
        public int? OrcDiaevtcob { get; set; }
        public int? OrcCttnum { get; set; }
        public DateTime? OrcCttdatemi { get; set; }
        public string OrcCttdoc { get; set; }
        public string OrcCttnomtest1 { get; set; }
        public string OrcCttdoctest1 { get; set; }
        public string OrcCttmontest2 { get; set; }
        public string OrcCttdoctest2 { get; set; }
        public string OrcInfevt { get; set; }
        public int? OrcValfixosalas { get; set; }
        public int? OrcCtlrenovacao { get; set; }
        public decimal? OrcCustomat { get; set; }
        public decimal? OrcCustoeqt { get; set; }
        public decimal? OrcCustoserv { get; set; }
        public decimal? OrcCustotec { get; set; }
        public decimal? OrcCustodesp { get; set; }
        public decimal? OrcCustobv { get; set; }
        public decimal? OrcCustoadian { get; set; }
        public decimal? OrcVlrttdespesa { get; set; }
        public decimal? OrcVlrttcomisao { get; set; }
        public decimal? OrcVlrttlucrobru { get; set; }
        public decimal? OrcVlrttlucroliq { get; set; }
        public decimal? OrcVlrttdespfixa { get; set; }
        public decimal? OrcVlrttdespvar { get; set; }
        public string OrcContato { get; set; }
        public string OrcContatoDdd { get; set; }
        public string OrcContatoFone { get; set; }
        public int? OrcComissaoflag { get; set; }
        public double? OrcComissaofun { get; set; }
        public string OrcDochtml { get; set; }
        public string OrcDocasp { get; set; }
        public string OrcDochtml2 { get; set; }
        public string OrcDochtml3 { get; set; }
        public int? CtldocId1 { get; set; }
        public int? CtldocId2 { get; set; }
        public int? CtldocId3 { get; set; }
        public int? ClatitId { get; set; }
        public int? SysVer { get; set; }
        public int? OrcNumcontrato { get; set; }
        public string OrcObsnota { get; set; }
        public decimal? OrcCttvalor { get; set; }
        public int? OrcCttcontrato { get; set; }
        public int? OrcCobdiaria { get; set; }
        public int? OrcUsuarioIdAlt { get; set; }
        public DateTime? OrcDataAlt { get; set; }
        public int? FunId1 { get; set; }
        public int? FunId2 { get; set; }
        public double? OrcComissaofun1 { get; set; }
        public double? OrcComissaofun2 { get; set; }
        public int? EqpId { get; set; }
        public string OrcResumo { get; set; }
        public int? CliforId2 { get; set; }
        public int? OrcCttDiafat { get; set; }
        public int? OrcCttDiavct { get; set; }
        public DateTime? OrcCttProxFat { get; set; }
        public int? OrcCttTipoContrato { get; set; }
        public DateTime? OrcCttInicio { get; set; }
        public DateTime? OrcCttTermino { get; set; }
        public DateTime? OrcCttPeriodoCobFim { get; set; }
        public int? OrcCttPrazoContrato { get; set; }
        public DateTime? OrcCttPeriodoCobIni { get; set; }
        public int? FunId3 { get; set; }
        public string OrcVersao { get; set; }
        public string OrcVersaoCad { get; set; }
        public int? UserId { get; set; }
    }
}
